[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false
# Automatically mark a test as "slow" after 60 seconds, then kill it after 180s
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.default.overrides]]
# Create-exe tests tend to be pretty flaky
filter = "test(create_exe)"
retries = 3

[[profile.default.overrides]]
# Snapshot tests tend to be flaky because they implicitly rely on how the OS will
# schedule threads. Our pipe flushing is also pretty unreliable.
filter = "test(snapshot)"
retries = 3
